// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzhSioZV0KQG0Wwe7W_bdfBZXHkwxU8GE',
    appId: '1:477421022483:web:5a2ad2e70d30852da6fee6',
    messagingSenderId: '477421022483',
    projectId: 'fleetop-inventory',
    authDomain: 'fleetop-inventory.firebaseapp.com',
    storageBucket: 'fleetop-inventory.firebasestorage.app',
    measurementId: 'G-0R5NVWW76B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1RC2Gd5hYS_jQMYib3F3xqE9k3sezD9I',
    appId: '1:477421022483:android:02cb6b0a7e4b06eca6fee6',
    messagingSenderId: '477421022483',
    projectId: 'fleetop-inventory',
    storageBucket: 'fleetop-inventory.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzhSioZV0KQG0Wwe7W_bdfBZXHkwxU8GE',
    appId: '1:477421022483:web:8c21c0fadcac3c30a6fee6',
    messagingSenderId: '477421022483',
    projectId: 'fleetop-inventory',
    authDomain: 'fleetop-inventory.firebaseapp.com',
    storageBucket: 'fleetop-inventory.firebasestorage.app',
    measurementId: 'G-YJV4MF0SF0',
  );

}