// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLqozoCR9QUy5Bezl9V4RLDqAJM_0gEo',
    appId: '1:690062728878:web:b5cdfc2d26888fb5aa973f',
    messagingSenderId: '690062728878',
    projectId: 'inventory-d5c1e',
    authDomain: 'inventory-d5c1e.firebaseapp.com',
    storageBucket: 'inventory-d5c1e.appspot.com',
    measurementId: 'G-ZR0TXE7LD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLqozoCR9QUy5Bezl9V4RLDqAJM_0gEo',
    appId: '1:690062728878:android:b3d97d848964a2b0aa973f',
    messagingSenderId: '690062728878',
    projectId: 'inventory-d5c1e',
    storageBucket: 'inventory-d5c1e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFNCD3ke5gHn1AjSE55-oPc7N7Yl1yPY',
    appId: '1:690062728878:web:b5cdfc2d26888fb5aa973f',
    messagingSenderId: '690062728878',
    projectId: 'inventory-d5c1e',
    authDomain: 'inventory-d5c1e.firebaseapp.com',
    storageBucket: 'inventory-d5c1e.appspot.com',
    measurementId: 'G-ZR0TXE7LD5',
  );

}